// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDki0tWKKFDaasfd2Cu5nqy8AacSYjRVUE',
    appId: '1:712554653780:web:937e03becbb5fabef165c1',
    messagingSenderId: '712554653780',
    projectId: 'bera-7e072',
    authDomain: 'bera-7e072.firebaseapp.com',
    storageBucket: 'bera-7e072.appspot.com',
    measurementId: 'G-WEXRPCM3KV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgvhliqs6SZdSOveWWmtBtrU8LbAm72rc',
    appId: '1:712554653780:android:136e958c6a2acbe9f165c1',
    messagingSenderId: '712554653780',
    projectId: 'bera-7e072',
    storageBucket: 'bera-7e072.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA71HBbln2npMPEEUySZO-Fq7W9d63TzVo',
    appId: '1:712554653780:ios:92bfac03b7ef9e48f165c1',
    messagingSenderId: '712554653780',
    projectId: 'bera-7e072',
    storageBucket: 'bera-7e072.appspot.com',
    androidClientId:
        '712554653780-ba76gr0phqopbescm6eq8t2si5v8pj9v.apps.googleusercontent.com',
    iosClientId:
        '712554653780-4bf8vcbb53d6qvaaj2utkibo6fimbbfj.apps.googleusercontent.com',
    iosBundleId: 'com.example.myFirstApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA71HBbln2npMPEEUySZO-Fq7W9d63TzVo',
    appId: '1:712554653780:ios:f53c9d6ce3f10c45f165c1',
    messagingSenderId: '712554653780',
    projectId: 'bera-7e072',
    storageBucket: 'bera-7e072.appspot.com',
    androidClientId:
        '712554653780-ba76gr0phqopbescm6eq8t2si5v8pj9v.apps.googleusercontent.com',
    iosClientId:
        '712554653780-ab7ac2ela0tgfdvi9n9to6m9l2g9difu.apps.googleusercontent.com',
    iosBundleId: 'com.example.myFirstApp.RunnerTests',
  );
}
